language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t prasaggarwal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prasaggarwal/react-test npm test -- --coverage

# Build prod level images
after_success:
  - docker build -t prasaggarwal/multi-client ./client
  - docker build -t prasaggarwal/multi-nginx ./nginx
  - docker build -t prasaggarwal/multi-server ./server
  - docker build -t prasaggarwal/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push prasaggarwal/multi-client
  - docker push prasaggarwal/multi-nginx
  - docker push prasaggarwal/multi-server
  - docker push prasaggarwal/multi-worker
